// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef image_test_window_h
#define image_test_window_h
#include <FL/Fl.H>
#include "image_test.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.H>

class image_test_window {
public:
  image_test_window();
  Fl_Double_Window *main_window;
  image_draw_area *draw_area;
private:
  inline void cb_Read_i(Fl_Button*, void*);
  static void cb_Read(Fl_Button*, void*);
public:
  void show( );
};
#endif
