// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef image_test_window_h
#define image_test_window_h
#include <FL/Fl.H>
#include "image_test.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Menu_Bar.H>

class image_test_window {
public:
  image_test_window();
  Fl_Double_Window *main_window;
  image_draw_area *draw_area;
private:
  inline void cb_Read_i(Fl_Button*, void*);
  static void cb_Read(Fl_Button*, void*);
  inline void cb_Read1_i(Fl_Button*, void*);
  static void cb_Read1(Fl_Button*, void*);
  inline void cb_Write_i(Fl_Button*, void*);
  static void cb_Write(Fl_Button*, void*);
  inline void cb_Write1_i(Fl_Button*, void*);
  static void cb_Write1(Fl_Button*, void*);
  inline void cb_Read2_i(Fl_Button*, void*);
  static void cb_Read2(Fl_Button*, void*);
  inline void cb_Write2_i(Fl_Button*, void*);
  static void cb_Write2(Fl_Button*, void*);
  inline void cb_Read3_i(Fl_Button*, void*);
  static void cb_Read3(Fl_Button*, void*);
  inline void cb_Write3_i(Fl_Button*, void*);
  static void cb_Write3(Fl_Button*, void*);
  inline void cb_Read4_i(Fl_Button*, void*);
  static void cb_Read4(Fl_Button*, void*);
  inline void cb_Write4_i(Fl_Button*, void*);
  static void cb_Write4(Fl_Button*, void*);
  static Fl_Menu_Item menu_[];
  inline void cb_Euclidean_i(Fl_Menu_*, void*);
  static void cb_Euclidean(Fl_Menu_*, void*);
  inline void cb_Figure_i(Fl_Menu_*, void*);
  static void cb_Figure(Fl_Menu_*, void*);
  inline void cb_Thresholding_i(Fl_Menu_*, void*);
  static void cb_Thresholding(Fl_Menu_*, void*);
  inline void cb_Labeling_i(Fl_Menu_*, void*);
  static void cb_Labeling(Fl_Menu_*, void*);
  inline void cb_Labeling1_i(Fl_Menu_*, void*);
  static void cb_Labeling1(Fl_Menu_*, void*);
  inline void cb_Thinning_i(Fl_Menu_*, void*);
  static void cb_Thinning(Fl_Menu_*, void*);
  inline void cb_Median_i(Fl_Menu_*, void*);
  static void cb_Median(Fl_Menu_*, void*);
  inline void cb_Erosion_i(Fl_Menu_*, void*);
  static void cb_Erosion(Fl_Menu_*, void*);
  inline void cb_Dilation_i(Fl_Menu_*, void*);
  static void cb_Dilation(Fl_Menu_*, void*);
  inline void cb_Opening_i(Fl_Menu_*, void*);
  static void cb_Opening(Fl_Menu_*, void*);
  inline void cb_Closing_i(Fl_Menu_*, void*);
  static void cb_Closing(Fl_Menu_*, void*);
  inline void cb_Reso_i(Fl_Menu_*, void*);
  static void cb_Reso(Fl_Menu_*, void*);
  inline void cb_Reso1_i(Fl_Menu_*, void*);
  static void cb_Reso1(Fl_Menu_*, void*);
  inline void cb_Reso2_i(Fl_Menu_*, void*);
  static void cb_Reso2(Fl_Menu_*, void*);
  inline void cb_Reso3_i(Fl_Menu_*, void*);
  static void cb_Reso3(Fl_Menu_*, void*);
  inline void cb_Reso4_i(Fl_Menu_*, void*);
  static void cb_Reso4(Fl_Menu_*, void*);
  inline void cb_Reso5_i(Fl_Menu_*, void*);
  static void cb_Reso5(Fl_Menu_*, void*);
  inline void cb_Read5_i(Fl_Button*, void*);
  static void cb_Read5(Fl_Button*, void*);
  inline void cb_Write5_i(Fl_Button*, void*);
  static void cb_Write5(Fl_Button*, void*);
public:
  void show( );
};
#endif
